-- 전체 시퀀스 드랍구문
SELECT 'DROP SEQUENCE '||SEQUENCE_NAME||';' FROM user_sequences;
DROP SEQUENCE SEQ_ADMIN_LOGIN_NO;
DROP SEQUENCE SEQ_ADMIN_NO;
DROP SEQUENCE SEQ_ALARM_TYPE_NO;
DROP SEQUENCE SEQ_ALARM_NO;
DROP SEQUENCE SEQ_BADGE_NO;
DROP SEQUENCE SEQ_BANNER_NO;
DROP SEQUENCE SEQ_COMMON_CATEGORY_NO;
DROP SEQUENCE SEQ_DM_MASSAGE_NO;
DROP SEQUENCE SEQ_DM_NO;
DROP SEQUENCE SEQ_FALLOW_NO;
DROP SEQUENCE SEQ_FAQ_NO;
DROP SEQUENCE SEQ_FREEBOARD_CATEGORY_NO;
DROP SEQUENCE SEQ_FREEBOARD_CMT_NO;
DROP SEQUENCE SEQ_FREEBOARD_IMG_NO;
DROP SEQUENCE SEQ_FREEBOARD_NO;
DROP SEQUENCE SEQ_GROUP_BOARD_CATEGORY_NO;
DROP SEQUENCE SEQ_GROUP_BOARD_CMT_NO;
DROP SEQUENCE SEQ_GROUP_BOARD_IMG_NO;
DROP SEQUENCE SEQ_GROUP_BOARD_NO;
DROP SEQUENCE SEQ_GROUP_CMT_NO;
DROP SEQUENCE SEQ_GROUP_IMG_NO;
-- 테이블명 RECRUIT_GROUP로 수정 (22-12-21)
DROP SEQUENCE SEQ_RECRUIT_GROUP_NO;
--GROUP 테이블 DROP (22-12-23)
DROP SEQUENCE SEQ_GROUP_NO;
DROP SEQUENCE SEQ_GROUP_PERIOD_NO;
DROP SEQUENCE SEQ_GROUP_TYPE_NO;
DROP SEQUENCE SEQ_GROUP_WAY_NO;
DROP SEQUENCE SEQ_ITEM_NO;
DROP SEQUENCE SEQ_JOB_CATEGORY_NO;
DROP SEQUENCE SEQ_KNOWLEDGE_ANSWER_NO;
DROP SEQUENCE SEQ_KNOWLEDGE_CATEGORY_NO;
DROP SEQUENCE SEQ_KNOWLEDGE_IMG_NO;
DROP SEQUENCE SEQ_KNOWLEDGE_QUESTION_NO;
DROP SEQUENCE SEQ_MAKE_GRASS_NO;
DROP SEQUENCE SEQ_MEMBER_GRADE_NO;
DROP SEQUENCE SEQ_MEMBER_NO;
DROP SEQUENCE SEQ_MENTORING_CATEGORY_NO;
DROP SEQUENCE SEQ_MENTORING_SCHEDULE_NO;
DROP SEQUENCE SEQ_MENTOR_NO;
DROP SEQUENCE SEQ_MENTOR_PAYMENT_NO;
DROP SEQUENCE SEQ_MENTOR_REVIEW_NO;
DROP SEQUENCE SEQ_MG_CMT_NO;
DROP SEQUENCE SEQ_MG_IMG_NO;
DROP SEQUENCE SEQ_NOTICE_CMT_NO;
DROP SEQUENCE SEQ_NOTICE_FILE_NO;
DROP SEQUENCE SEQ_NOTICE_IMG_NO;
DROP SEQUENCE SEQ_NOTICE_NO;
DROP SEQUENCE SEQ_POPUP_NO;
DROP SEQUENCE SEQ_QUESTION_BOARD_CMT_NO;
DROP SEQUENCE SEQ_QUESTION_BOARD_IMG_NO;
DROP SEQUENCE SEQ_QUESTION_BOARD_NO;
DROP SEQUENCE SEQ_RECRUIT_LIST_NO;
DROP SEQUENCE SEQ_RECRUIT_QUESTION_NO;
DROP SEQUENCE SEQ_RECRUIT_REPLY_NO;
DROP SEQUENCE SEQ_TAG_NO;
-- 오타수정 SEQ_TECK_STACK_NO -> SEQ_TECH_STACK_NO (22-12-21)
DROP SEQUENCE SEQ_TECH_STACK_NO;
-- 테이블 추가 (22-12-22)
DROP SEQUENCE SEQ_TECH_STACK_TYPE_NO;
DROP SEQUENCE SEQ_VISITOR_NO;
DROP SEQUENCE SEQ_PAGE_VIEW_NO;

-- 전체 테이블 드랍구문
SELECT 'DROP TABLE "' || TABLE_NAME || '" CASCADE CONSTRAINTS;' FROM user_tables;
DROP TABLE "MEMBER" CASCADE CONSTRAINTS;
DROP TABLE "MEMBER_GRADE" CASCADE CONSTRAINTS;
DROP TABLE "ALARM" CASCADE CONSTRAINTS;
DROP TABLE "FOLLOW" CASCADE CONSTRAINTS;
DROP TABLE "ALARM_TYPE" CASCADE CONSTRAINTS;
DROP TABLE "MEMBER_ITEM" CASCADE CONSTRAINTS;
DROP TABLE "MEMBER_BADGE" CASCADE CONSTRAINTS;
DROP TABLE "DM" CASCADE CONSTRAINTS;
DROP TABLE "DM_MASSAGE" CASCADE CONSTRAINTS;
-- 테이블명 RECRUIT_GROUP로 수정 (22-12-21)
DROP TABLE "RECRUIT_GROUP" CASCADE CONSTRAINTS;
DROP TABLE "NOTICE" CASCADE CONSTRAINTS;
DROP TABLE "KNOWLEDGE_QUESTION" CASCADE CONSTRAINTS;
DROP TABLE "MENTOR" CASCADE CONSTRAINTS;
DROP TABLE "RECRUIT_QUESTION" CASCADE CONSTRAINTS;
DROP TABLE "NOTICE_CMT" CASCADE CONSTRAINTS;
DROP TABLE "GROUP_CMT" CASCADE CONSTRAINTS;
DROP TABLE "NOTICE_FILE" CASCADE CONSTRAINTS;
DROP TABLE "GROUP_IMG" CASCADE CONSTRAINTS;
DROP TABLE "FAQ" CASCADE CONSTRAINTS;
DROP TABLE "GROUP_SCRAP" CASCADE CONSTRAINTS;
DROP TABLE "TECH_STACK" CASCADE CONSTRAINTS;
-- 테이블 추가 (22-12-22)
DROP TABLE "TECH_STACK_TYPE" CASCADE CONSTRAINTS;
DROP TABLE "FAQ_IMG" CASCADE CONSTRAINTS;
DROP TABLE "KNOWLEDGE_ANSWER" CASCADE CONSTRAINTS;
DROP TABLE "RECRUIT_LIST" CASCADE CONSTRAINTS;
DROP TABLE "RECRUIT_REPLY" CASCADE CONSTRAINTS;
DROP TABLE "QUESTION_BOARD" CASCADE CONSTRAINTS;
DROP TABLE "QUESTION_BOARD_CMT" CASCADE CONSTRAINTS;
DROP TABLE "QUESTION_BOARD_IMG" CASCADE CONSTRAINTS;
DROP TABLE "COMMON_CATEGORY" CASCADE CONSTRAINTS;
DROP TABLE "BADGE" CASCADE CONSTRAINTS;
DROP TABLE "ITEM" CASCADE CONSTRAINTS;
DROP TABLE "ADMIN" CASCADE CONSTRAINTS;
DROP TABLE "KNOWLEDGE_IMG" CASCADE CONSTRAINTS;
DROP TABLE "KNOWLEDGE_LIKE_HATE" CASCADE CONSTRAINTS;
DROP TABLE "KNOWLEDGE_SCRAP" CASCADE CONSTRAINTS;
DROP TABLE "KNOWLEDGE_CATEGORY" CASCADE CONSTRAINTS;
DROP TABLE "MAKE_GRASS" CASCADE CONSTRAINTS;
DROP TABLE "MENTORING_SCHEDULE" CASCADE CONSTRAINTS;
DROP TABLE "ADMIN_LOGIN" CASCADE CONSTRAINTS;
DROP TABLE "BANNER" CASCADE CONSTRAINTS;
DROP TABLE "MG_CMT" CASCADE CONSTRAINTS;
DROP TABLE "MG_IMG" CASCADE CONSTRAINTS;
DROP TABLE "MENTORING_PAYMENT" CASCADE CONSTRAINTS;
DROP TABLE "POPUP" CASCADE CONSTRAINTS;
DROP TABLE "MG_SCRAP" CASCADE CONSTRAINTS;
DROP TABLE "GROUP_TYPE" CASCADE CONSTRAINTS;
DROP TABLE "GROUP_WAY" CASCADE CONSTRAINTS;
DROP TABLE "GROUP_PERIOD" CASCADE CONSTRAINTS;
DROP TABLE "MENTORING_REVIEW" CASCADE CONSTRAINTS;
DROP TABLE "MENTORING_CATEGORY" CASCADE CONSTRAINTS;
DROP TABLE "FREE_BOARD" CASCADE CONSTRAINTS;
DROP TABLE "FREE_BOARD_CMT" CASCADE CONSTRAINTS;
DROP TABLE "FREE_BOARD_IMG" CASCADE CONSTRAINTS;
DROP TABLE "FREE_BOARD_LIKE_HATE" CASCADE CONSTRAINTS;
DROP TABLE "FREE_BOARD_SCRAP" CASCADE CONSTRAINTS;
DROP TABLE "FREE_BOARD_CATEGORY" CASCADE CONSTRAINTS;
DROP TABLE "GROUP_LIKE_HATE" CASCADE CONSTRAINTS;
DROP TABLE "MG_LIKE_HATE" CASCADE CONSTRAINTS;
DROP TABLE "GROUP_CMT_LIKE_HATE" CASCADE CONSTRAINTS;
DROP TABLE "MG_CMT_LIKE_HATE" CASCADE CONSTRAINTS;
DROP TABLE "FREE_BOARD_CMT_LIKE_HATE" CASCADE CONSTRAINTS;
DROP TABLE "K_CMT_LIKE_HATE" CASCADE CONSTRAINTS;
DROP TABLE "GROUP_TECH_STACK" CASCADE CONSTRAINTS;
DROP TABLE "MEMBER_STACK" CASCADE CONSTRAINTS;
DROP TABLE "TAG" CASCADE CONSTRAINTS;
DROP TABLE "MG_TAG" CASCADE CONSTRAINTS;
DROP TABLE "GROUP_TAG" CASCADE CONSTRAINTS;
DROP TABLE "KNOWLEDGE_TAG" CASCADE CONSTRAINTS;
DROP TABLE "GROUP_BOARD" CASCADE CONSTRAINTS;
DROP TABLE "GROUP_BOARD_CMT" CASCADE CONSTRAINTS;
DROP TABLE "GROUP_BOARD_IMG" CASCADE CONSTRAINTS;
DROP TABLE "GROUP_BOARD_CATEGORY" CASCADE CONSTRAINTS;
DROP TABLE "JOB_CATEGORY" CASCADE CONSTRAINTS;
DROP TABLE "NOTICE_ADMIN" CASCADE CONSTRAINTS;
DROP TABLE "VISITOR" CASCADE CONSTRAINTS;
DROP TABLE "PAGE_VIEW" CASCADE CONSTRAINTS;

----------------------------
--멤버 어드민확인 디폴트값 추가 (12/21)
--멤버 이메일 인증 확인 칼럼 추가 (12/22)
----------------------------
CREATE TABLE "MEMBER" (
	"NO"	NUMBER		NOT NULL,
	"ID"	VARCHAR(300)		NOT NULL,
	"PWD"	VARCHAR(100)		NOT NULL,
	"PHONE"	CHAR(11)		NOT NULL,
	"NICK"	VARCHAR(100)		NOT NULL,
	"ENROLL_DATE"	TIMESTAMP	DEFAULT SYSDATE	NOT NULL,
	"QUIT_YN"	CHAR(1)	DEFAULT 'N' CHECK (QUIT_YN IN ('Y', 'N'))	NOT NULL,
	"MODIFY_DATE"	TIMESTAMP	DEFAULT SYSDATE	NOT NULL,
	"IMG_PATH"	VARCHAR2(1000)		NULL,
	"INTRO"	CLOB		NULL,
	"ACCUM_TOKEN"	NUMBER	DEFAULT 0	NOT NULL,
	"HOLD_TOKEN"	NUMBER	DEFAULT 0	NOT NULL,
	"TECH_STACK_NO"	VARCHAR2(1000)		NULL,
	"ADMIN_YN"	CHAR(1)	DEFAULT 'N' CHECK (ADMIN_YN IN ('Y', 'N'))	NOT NULL,
	"EMAIL_AUTH"	CHAR(1)	DEFAULT '0' CHECK (EMAIL_AUTH IN ('0', '1'))	NOT NULL
);

CREATE TABLE "MEMBER_GRADE" (
	"NO"	NUMBER		NOT NULL,
	"NAME"	VARCHAR2(100)		NOT NULL,
	"IMG_PATH"	VARCHAR2(1000)		NOT NULL,
	"ACCUM_TOKEN"	NUMBER	DEFAULT 0	NOT NULL
);
--1/5 루트 제거, 체크 확인 유무 칼럼 추가
CREATE TABLE "ALARM" (
	"NO"	NUMBER		NOT NULL,
	"SEND_M_NO"	NUMBER		NOT NULL,
	"RECE_M_NO"	NUMBER		NOT NULL,
	"ALARM_TYPE_NO"	NUMBER		NOT NULL,
	"MASSAGE"	VARCHAR2(4000)		NOT NULL,
	"ALARM_TIME"	TIMESTAMP	DEFAULT SYSDATE	NOT NULL,
	"CHECK_TIME"	TIMESTAMP	DEFAULT SYSDATE	NOT NULL,
	"CHECK_YN"	CHAR(1)	DEFAULT 'N' CHECK(CHECK_YN IN ('Y' , 'N'))	NOT NULL
);

CREATE TABLE "FOLLOW" (
	"NO"	NUMBER		NOT NULL,
	"FOLLOWING_NO"	NUMBER		NOT NULL,
	"FOLLOWER_NO"	NUMBER		NOT NULL
);

CREATE TABLE "ALARM_TYPE" (
	"NO"	NUMBER		NOT NULL,
	"NAME"	VARCHAR2(100)		NOT NULL
);

CREATE TABLE "MEMBER_ITEM" (
	"M_NO"	NUMBER		NOT NULL,
	"ITEM_NO"	NUMBER		NOT NULL
);

CREATE TABLE "MEMBER_BADGE" (
	"M_NO"	NUMBER		NOT NULL,
	"BADGE_NO"	NUMBER		NOT NULL
);

CREATE TABLE "DM" (
	"NO"	NUMBER		NOT NULL,
	"SEND_M_NO"	NUMBER		NOT NULL,
	"RECE_M_NO"	NUMBER		NOT NULL,
	"ENROLL_DATE"	TIMESTAMP	DEFAULT SYSDATE	NOT NULL,
	"DELETE_YN"	CHAR(1)	DEFAULT 'N' CHECK(DELETE_YN IN ('Y' , 'N'))	NOT NULL
);

--1/8 칼럼 추가
CREATE TABLE "DM_MASSAGE" (
	"NO"	NUMBER		NOT NULL,
	"DM_NO"	NUMBER		NOT NULL,
	"SEND_M_NO"	NUMBER		NOT NULL,
	"RECE_M_NO"	NUMBER		NOT NULL,
	"CONTENT"	VARCHAR2(4000)		NOT NULL,
	"ENROLL_DATE"	TIMESTAMP	DEFAULT SYSDATE	NOT NULL
);

CREATE TABLE "RECRUIT_GROUP" (
	"NO"	NUMBER		NOT NULL,
	"WRITER"	NUMBER		NOT NULL,
	"G_TYPE_NO"	NUMBER		NOT NULL,
	"G_WAY_NO"	NUMBER		NOT NULL,
	"G_PERIOD_NO"	NUMBER		NOT NULL,
	"NUMBER_PEOPLE"	NUMBER		NOT NULL,
	"TECH_STACK_NO"	VARCHAR2(100)		NOT NULL,
	"START_DATE"	TIMESTAMP		NOT NULL,
	"START_TIME"	VARCHAR2(100)		NOT NULL,
	"END_TIME"	VARCHAR2(100)		NOT NULL,
	-- 제목 칼럼 추가함(2022-12-19)
	"TITLE"	VARCHAR2(1000)		NOT NULL,
	"INTRO"	CLOB		NOT NULL,
	"PLACE"	VARCHAR2(1000)		NULL,
	-- 주소 칼럼 추가함(2022-12-19)
	"ADDRESS"	VARCHAR2(1000)		NULL,
	"HIT"	NUMBER		NOT NULL,
	"CLOSING_YN"	CHAR(1)	DEFAULT 'N' CHECK(CLOSING_YN IN ('Y', 'N'))	NOT NULL,
	"DELETE_YN"	CHAR(1)	DEFAULT 'N' CHECK(DELETE_YN IN ('Y', 'N'))	NOT NULL,
	"MODIFY_DATE"	TIMESTAMP	DEFAULT SYSDATE	NOT NULL,
	"ENROLL_DATE"	TIMESTAMP	DEFAULT SYSDATE	NOT NULL,
	"NAME"	VARCHAR2(100)		NULL,
	"IMG_PATH"	VARCHAR2(1000)		NULL
);

CREATE TABLE "NOTICE" (
	"NO"	NUMBER		NOT NULL,
	"CATE_NO"	NUMBER		NOT NULL,
	"WRITER"	NUMBER		NOT NULL,
	"TITLE"	VARCHAR2(1000)		NOT NULL,
	"CONTENT"	CLOB		NOT NULL,
	"ENROLL_DATE"	TIMESTAMP		NULL,
	"DELETE_YN"	CHAR(1)	DEFAULT 'N' CHECK(DELETE_YN IN ('Y' , 'N'))	NOT NULL,
	"MODIFY_DATE"	TIMESTAMP	DEFAULT SYSDATE	NOT NULL,
	"HIT"	NUMBER		NOT NULL,
	"STATUS"	NUMBER		NULL,
"CATEGORY"	VARCHAR2(100) NULL,
"KEYWORD"	VARCHAR2(300) NULL
);

CREATE TABLE "KNOWLEDGE_QUESTION" (
	"NO"	NUMBER		NOT NULL,
	"WRITER"	NUMBER		NOT NULL,
	"CATE_NO"	NUMBER		NOT NULL,
	"TITLE"	VARCHAR2(1000)		NOT NULL,
	"CONTENT"	CLOB		NOT NULL,
	"ENROLL_DATE"	TIMESTAMP	DEFAULT SYSDATE	NOT NULL,
	"DELETE_YN"	CHAR(1)	DEFAULT 'N' CHECK(DELETE_YN IN ('Y' , 'N'))	NOT NULL,
	"MODIFY_DATE"	TIMESTAMP	DEFAULT SYSDATE	NOT NULL,
	"HIT"	NUMBER	DEFAULT 0	NOT NULL
);

CREATE TABLE "MENTOR" (
	"NO"	NUMBER		NOT NULL,
	"WRITER"	NUMBER		NOT NULL,
	"CATE_NO"	NUMBER		NOT NULL,
	"JOB"	NUMBER		NULL,
	"EMAIL"	VARCHAR2(300)		NOT NULL,
	"NAME"	VARCHAR2(100)		NOT NULL,
	"PHONE_NO"	VARCHAR2(100)		NOT NULL,
	"INTRO"	VARCHAR2(4000)		NOT NULL,
	"LINK"	VARCHAR2(2000)		NOT NULL,
	"ENROLL_DATE"	TIMESTAMP	DEFAULT SYSDATE	NOT NULL,
	"ACCOUNT_BANK" NUMBER NOT NULL,
	"ACCOUNT_NO"	VARCHAR2(100)		NOT NULL,
	"TITLE"	VARCHAR2(1000)		NULL,
	"CAREER"	VARCHAR2(1000)		NULL,
	"EMPLOYED_YN"	CHAR(1)		NULL,
	"PRICE"	NUMBER		NULL,
	"MAX_PEOPLE"	NUMBER		NULL,
	"MAX_HOUR"	VARCHAR2(100)		NULL,
	"WELCOME_POST"	VARCHAR2(1000)		NULL,
	"WRITE_DATE"	TIMESTAMP	DEFAULT SYSDATE	NULL,
	"OPEN_YN"	CHAR(1)	DEFAULT 'Y' CHECK(OPEN_YN IN ('Y' , 'N'))	NULL,
	"MODIFY_DATE"	TIMESTAMP		NULL,
	"HIT"	NUMBER		NULL,
-- 23 01 05 추가
	"DETAIL" CLOB NULL,
	"CURRENT_JOB" VARCHAR2(100) NULL,
	"M_EMAIL" VARCHAR2(300) NULL,
	"M_PHONE_NO" VARCHAR2(100) NULL
);

CREATE TABLE "RECRUIT_QUESTION" (
	"NO"	NUMBER		NOT NULL,
	"G_NO"	NUMBER		NOT NULL,
	"QUESTION"	VARCHAR2(1000)		NOT NULL,
	"DELETE_YN"	CHAR(1)		NULL,
	"MODIFY_DATE"	TIMESTAMP		NULL
);

CREATE TABLE "NOTICE_CMT" (
	"NO"	NUMBER		NOT NULL,
	"N_NO"	NUMBER		NOT NULL,
	"WRITER"	NUMBER		NOT NULL,
	"ENROLL_DATE"	TIMESTAMP	DEFAULT SYSDATE	NOT NULL,
	"DELETE_YN"	CHAR(1)	DEFAULT 'N' CHECK(DELETE_YN IN ('Y' , 'N'))	NOT NULL,
	"MODIFY_DATE"	TIMESTAMP	DEFAULT SYSDATE	NOT NULL,
	"CONTENT"	CLOB		NOT NULL,
	"DEPTH"	NUMBER		NOT NULL,
	"GROUP"	NUMBER		NOT NULL
);

CREATE TABLE "GROUP_CMT" (
	"NO"	NUMBER		NOT NULL,
	"G_NO"	NUMBER		NOT NULL,
	"WRITER"	NUMBER		NOT NULL,
	"CONTENT"	CLOB		NOT NULL,
	"ENROLL_DATE"	TIMESTAMP	DEFAULT SYSDATE	NOT NULL,
	"MODIFY_DATE"	TIMESTAMP	DEFAULT SYSDATE	NOT NULL,
	"DELETE_YN"	CHAR(1)	DEFAULT 'N' CHECK(DELETE_YN IN ('Y', 'N'))	NOT NULL,
	"DEPTH"	NUMBER		NOT NULL,
	"GROUP"	NUMBER		NOT NULL
);

CREATE TABLE "NOTICE_FILE" (
	"NO"	NUMBER		NOT NULL,
	"N_NO"	NUMBER		NOT NULL,
	"IMG_PATH"	VARCHAR2(2000)		NOT NULL,
	"ENROLL_DATE"	TIMESTAMP	DEFAULT SYSDATE	NOT NULL,
	"THUMB_YN"	CHAR(1)	DEFAULT 'N' CHECK(THUMB_YN IN ('Y' , 'N'))	NOT NULL
);

CREATE TABLE "GROUP_IMG" (
	"NO"	NUMBER		NOT NULL,
	"G_NO"	NUMBER		NOT NULL,
	"IMG_PATH"	VARCHAR2(1000)		NOT NULL,
	"ENROLL_DATE"	TIMESTAMP	DEFAULT SYSDATE	NOT NULL,
	"THUMB_YN"	CHAR(1)	DEFAULT 'N' CHECK(THUMB_YN IN ('Y', 'N'))	NOT NULL
);

CREATE TABLE "FAQ" (
	"NO"	NUMBER		NOT NULL,
	"CATE_NO"	NUMBER		NOT NULL,
	"WRITER"	NUMBER		NOT NULL,
	"TITLE"	VARCHAR2(1000)		NOT NULL,
	"CONTENT"	CLOB		NOT NULL,
	"ENROLL_DATE"	TIMESTAMP	DEFAULT SYSDATE	NOT NULL,
	"DELETE_YN"	CHAR(1)	DEFAULT 'N' CHECK(DELETE_YN IN ('Y' , 'N'))	NOT NULL,
	"MODIFY_DATE"	TIMESTAMP	DEFAULT SYSDATE	NOT NULL
);

CREATE TABLE "GROUP_SCRAP" (
	"M_NO"	NUMBER		NOT NULL,
	"G_NO"	NUMBER		NOT NULL
);

CREATE TABLE "TECH_STACK" (
	"NO"	NUMBER		NOT NULL,
-- 테이블 추가 (22-12-22)
  "TYPE_NO"	NUMBER		NOT NULL,
	"NAME"	VARCHAR2(100)		NOT NULL,
	"IMG_PATH"	VARCHAR2(1000)		NOT NULL
);

-- 테이블 추가 (22-12-22)
CREATE TABLE "TECH_STACK_TYPE" (
	"NO"	NUMBER		NOT NULL,
	"NAME"	VARCHAR2(100)		NOT NULL
);

CREATE TABLE "FAQ_IMG" (
	"NO"	NUMBER		NOT NULL,
	"F_NO"	NUMBER		NOT NULL,
	"IMG_PATH"	VARCHAR2(2000)		NOT NULL,
	"ENROLL_DATE"	TIMESTAMP	DEFAULT SYSDATE	NOT NULL,
	"THUMB_YN"	CHAR(1)	DEFAULT 'N' CHECK(THUMB_YN IN ('Y' , 'N'))	NOT NULL
);

CREATE TABLE "KNOWLEDGE_ANSWER" (
	"NO"	NUMBER		NOT NULL,
	"Q_NO"	NUMBER		NOT NULL,
	"WRITER"	NUMBER		NOT NULL,
	"CONTENT"	CLOB		NOT NULL,
	"ENROLL_DATE"	TIMESTAMP	DEFAULT SYSDATE	NOT NULL,
	"DELETE_YN"	CHAR(1)	DEFAULT 'N' CHECK(DELETE_YN IN ('Y' , 'N'))	NOT NULL,
	"MODIFY_DATE"	TIMESTAMP	DEFAULT SYSDATE	NOT NULL,
	"SELECT_YN"	CHAR(1)	DEFAULT 'N' CHECK(SELECT_YN IN ('Y' , 'N'))	NOT NULL,
	"DEPTH"	NUMBER		NOT NULL,
	"GROUP"	NUMBER		NOT NULL
);

CREATE TABLE "RECRUIT_LIST" (
	"NO"	NUMBER		NOT NULL,
	"G_NO"	NUMBER		NOT NULL,
	"M_NO"	NUMBER		NOT NULL,
	"ENROLL_DATE"	TIMESTAMP	DEFAULT SYSDATE	NOT NULL,
	"STATUS"	CHAR(1)	DEFAULT 'A' CHECK(STATUS IN ('A', 'B', 'C', 'D', 'E', 'F'))	NOT NULL
);

CREATE TABLE "RECRUIT_REPLY" (
	"NO"	NUMBER		NOT NULL,
	"RECRUIT_QUESTION_NO"	NUMBER		NOT NULL,
	"RECRUIT_LIST_NO"	NUMBER		NOT NULL,
	"CONTENT"	VARCHAR2(1000)		NOT NULL
);

CREATE TABLE "QUESTION_BOARD" (
	"NO"	NUMBER		NOT NULL,
	"CATE_NO"	NUMBER		NOT NULL,
	"WRITER"	NUMBER		NOT NULL,
	"TITLE"	VARCHAR2(1000)		NOT NULL,
	"CONTENT"	CLOB		NOT NULL,
	"ENROLL_DATE"	TIMESTAMP	DEFAULT SYSDATE	NOT NULL,
	"DELETE_YN"	CHAR(1)	DEFAULT 'N' CHECK(DELETE_YN IN ('Y' , 'N'))	NOT NULL,
	"MODIFY_DATE"	TIMESTAMP	DEFAULT SYSDATE	NOT NULL
);

CREATE TABLE "QUESTION_BOARD_CMT" (
	"NO"	NUMBER		NOT NULL,
	"Q_NO"	NUMBER		NOT NULL,
	"WRITER"	NUMBER		NOT NULL,
	"ENROLL_DATE"	TIMESTAMP	DEFAULT SYSDATE	NOT NULL,
	"DELETE_YN"	CHAR(1)	DEFAULT 'N' CHECK(DELETE_YN IN ('Y' , 'N'))	NOT NULL,
	"MODIFY_DATE"	TIMESTAMP	DEFAULT SYSDATE	NOT NULL,
	"CONTENT"	CLOB		NOT NULL,
	"DEPTH"	NUMBER		NOT NULL,
	"GROUP"	NUMBER		NOT NULL
);

CREATE TABLE "QUESTION_BOARD_IMG" (
	"NO"	NUMBER		NOT NULL,
	"Q_NO"	NUMBER		NOT NULL,
	"IMG_PATH"	VARCHAR2(2000)		NOT NULL,
	"ENROLL_DATE"	TIMESTAMP	DEFAULT SYSDATE	NOT NULL,
	"THUMB_YN"	CHAR(1)	DEFAULT 'N' CHECK(THUMB_YN IN ('Y' , 'N'))	NOT NULL
);

CREATE TABLE "COMMON_CATEGORY" (
	"NO"	NUMBER		NOT NULL,
	"NAME"	VARCHAR2(1000)		NOT NULL,
	"COUNT"	NUMBER		NULL
);
--1/2 상태 칼럼 추가
CREATE TABLE "BADGE" (
	"NO"	NUMBER		NOT NULL,
	"NAME"	VARCHAR2(1000)		NOT NULL,
	"INFO"	VARCHAR2(1000)		NOT NULL,
	"IMG_PATH"	VARCHAR2(2000)		NOT NULL,
	"STATUS"	CHAR(1)	DEFAULT 'O' CHECK(STATUS IN ('O' , 'X'))	NOT NULL
);

--1/4 CLASS_NAME 칼럼 널 허용
CREATE TABLE "ITEM" (
	"NO"	NUMBER		NOT NULL,
	"NAME"	VARCHAR2(1000)		NOT NULL,
	"INFO"	VARCHAR2(1000)		NOT NULL,
	"CLASS_NAME"	VARCHAR2(300)		NULL,
	"CLASS_STYLE"	VARCHAR2(1000)		NULL,
	"PRICE"	NUMBER		NOT NULL,
	"IMG_PATH"	VARCHAR2(2000)		NOT NULL,
	"DELETE_YN"	CHAR(1)	DEFAULT 'N' CHECK(DELETE_YN IN ('Y' , 'N'))	NOT NULL
);

CREATE TABLE "ADMIN" (
	"NO"	NUMBER		NOT NULL,
	"ID"	VARCHAR2(300)		NOT NULL,
	"PWD"	VARCHAR2(500)		NOT NULL,
	"NICK"	VARCHAR2(500)		NOT NULL,
	"IMG_PATH"	VARCHAR2(2000),
  "DELETE_YN"	CHAR(1) DEFAULT 'N' CHECK(DELETE_YN IN ('Y' , 'N'))	NOT NULL,
  "ENROLL_DATE"	TIMESTAMP	DEFAULT SYSDATE	NOT NULL
);
--1/5 IMG_PATH 칼럼 널 허용
--1/7 DELETE_YN, ENROLL_DATE 칼럼 추가

CREATE TABLE "KNOWLEDGE_IMG" (
	"NO"	NUMBER		NOT NULL,
	"Q_NO"	NUMBER		NOT NULL,
	"IMG_PATH"	VARCHAR2(1000)		NOT NULL,
	"ENROLL_DATE"	TIMESTAMP	DEFAULT SYSDATE	NOT NULL,
	"THUMB_YN"	CHAR(1)	DEFAULT 'N' CHECK(THUMB_YN IN ('Y' , 'N'))	NOT NULL
);

CREATE TABLE "KNOWLEDGE_LIKE_HATE" (
	"NO"	NUMBER		NOT NULL,
	"M_NO"	NUMBER		NOT NULL,
	"STATUS"	CHAR(1)		NOT NULL
);

CREATE TABLE "KNOWLEDGE_SCRAP" (
	"Q_NO"	NUMBER		NOT NULL,
	"M_NO"	NUMBER		NOT NULL
);

CREATE TABLE "KNOWLEDGE_CATEGORY" (
	"NO"	NUMBER		NOT NULL,
	"NAME"	VARCHAR2(100)		NOT NULL
);

CREATE TABLE "MAKE_GRASS" (
	"NO"	NUMBER		NOT NULL,
	"WRITER"	NUMBER		NOT NULL,
	"TITLE"	VARCHAR2(1000)		NOT NULL,
	"CONTENT"	CLOB		NOT NULL,
	"LEARN_TIME"	VARCHAR2(100)		NOT NULL,
	"ENROLL_DATE"	TIMESTAMP	DEFAULT SYSDATE	NOT NULL,
	"DELETE_YN"	CHAR(1)	DEFAULT 'N' CHECK(DELETE_YN IN ('Y' , 'N'))	NOT NULL,
	"MODIFY_DATE"	TIMESTAMP	DEFAULT SYSDATE	NOT NULL,
	"HIT"	NUMBER	DEFAULT '0'	NOT NULL
);

CREATE TABLE "MENTORING_SCHEDULE" (
	"NO"	NUMBER		NOT NULL,
	"MENTOR_NO"	NUMBER		NOT NULL,
	"ABLE_DAY"	VARCHAR2(100)		NOT NULL,
	"ABLE_TIME"	VARCHAR2(100)		NOT NULL
);

CREATE TABLE "ADMIN_LOGIN" (
	"NO"	NUMBER		NOT NULL,
	"A_NO"	NUMBER		NOT NULL,
	"ACCESS_TIME"	TIMESTAMP	DEFAULT SYSDATE	NOT NULL,
	"ACCESS_IP"	VARCHAR2(500)		NOT NULL,
  "LOGIN_YN"	CHAR(1)	NOT NULL
);

--01/06 COLOR 칼럼 추가
CREATE TABLE "BANNER" (
	"NO"	NUMBER		NOT NULL,
	"TITLE"	VARCHAR2(1000)		NOT NULL,
	"IMG_PATH"	VARCHAR2(2000)		NOT NULL,
	"LINK"	VARCHAR2(1000)		NULL,
	"ENROLL_DATE"	TIMESTAMP	DEFAULT SYSDATE	NOT NULL,
	"STATUS"	CHAR(1)	DEFAULT 'C' CHECK(STATUS IN ('A', 'B', 'C', 'D'))	NOT NULL,
	"START_DATE"	TIMESTAMP	DEFAULT SYSDATE	NOT NULL,
	"END_DATE"	TIMESTAMP		NOT NULL,
  "COLOR"	VARCHAR2(100)		NULL
);

CREATE TABLE "MG_CMT" (
	"NO"	NUMBER		NOT NULL,
	"MG_NO"	NUMBER		NOT NULL,
	"WRITER"	NUMBER		NOT NULL,
	"CONTENT"	CLOB		NOT NULL,
	"ENROLL_DATE"	TIMESTAMP	DEFAULT SYSDATE	NOT NULL,
	"DELETE_YN"	CHAR(1)	DEFAULT 'N' CHECK(DELETE_YN IN ('Y' , 'N'))	NOT NULL,
	"MODIFY_DATE"	TIMESTAMP	DEFAULT SYSDATE	NOT NULL,
	"DEPTH"	NUMBER		NOT NULL,
	"GROUP"	NUMBER		NOT NULL
);

CREATE TABLE "MG_IMG" (
	"NO"	NUMBER		NOT NULL,
	"MG_NO"	NUMBER		NOT NULL,
	"IMG_PATH"	VARCHAR2(1000)		NOT NULL,
	"ENROLL_DATE"	TIMESTAMP	DEFAULT SYSDATE	NOT NULL,
	"THUMB_YN"	CHAR(1)	DEFAULT 'N' CHECK(THUMB_YN IN ('Y' , 'N'))	NOT NULL
);

CREATE TABLE "MENTORING_PAYMENT" (
	"NO"	NUMBER		NOT NULL,
	"MENTOR_NO"	NUMBER		NOT NULL,
	"M_NO"	NUMBER		NOT NULL,
	"RESERVATION_DATE"	VARCHAR2(300)		NOT NULL,
	"RESERVATION_TIME"	VARCHAR2(300)		NOT NULL,
	"PHONE_NO"	VARCHAR2(100)		NOT NULL,
	"EMAIL"	VARCHAR2(300)		NOT NULL,
	"MESSAGE"	VARCHAR2(1000)		NULL,
	"PRICE"	NUMBER		NOT NULL,
	"PAYMENT_TYPE"	VARCHAR2(1000)		NOT NULL,
	"PAYMENT_DATE"	TIMESTAMP	DEFAULT SYSDATE	NOT NULL,
	"CANCEL_YN"	CHAR(1)	DEFAULT 'N' CHECK(CANCEL_YN IN ('Y' , 'N'))	NOT NULL,
-- 2023 01 05 추가
  "APPLY_YN" CHAR(1) DEFAULT 'N' CHECK(APPLY_YN IN ('Y','N','R'))	NOT NULL,
-- 2023 01 08 추가
	"COMPLETE_YN" CHAR(1) DEFAULT 'N' CHECK(COMPLETE_YN IN ('Y', 'N'))
);

CREATE TABLE "POPUP" (
	"NO"	NUMBER		NOT NULL,
	"TITLE"	VARCHAR2(1000)		NOT NULL,
	"IMG_PATH"	VARCHAR2(2000)		NOT NULL,
	"LOCATION"	VARCHAR2(300)		NOT NULL,
	"APPLY"	VARCHAR2(500)		NOT NULL,
	"LINK"	VARCHAR2(1000)		NULL,
	"ENROLL_DATE"	TIMESTAMP	DEFAULT SYSDATE	NOT NULL,
	"STATUS"	CHAR(1)	DEFAULT 'C' CHECK(STATUS IN ('A', 'B', 'C', 'D'))	NOT NULL,
	"START_DATE"	TIMESTAMP	DEFAULT SYSDATE	NOT NULL,
	"END_DATE"	TIMESTAMP		NOT NULL
);

CREATE TABLE "MG_SCRAP" (
	"NO"	NUMBER		NOT NULL,
	"M_NO"	NUMBER		NOT NULL
);

CREATE TABLE "GROUP_TYPE" (
	"NO"	NUMBER		NOT NULL,
	"NAME"	VARCHAR2(100)		NOT NULL
);

CREATE TABLE "GROUP_WAY" (
	"NO"	NUMBER		NOT NULL,
	"NAME"	VARCHAR2(100)		NOT NULL
);

CREATE TABLE "GROUP_PERIOD" (
	"NO"	NUMBER		NOT NULL,
	"NAME"	VARCHAR2(100)		NOT NULL
);

CREATE TABLE "MENTORING_REVIEW" (
	"NO"	NUMBER		NOT NULL,
	"MENTOR_NO"	NUMBER		NOT NULL,
	"WRITER"	NUMBER		NOT NULL,
	"CONTENT"	VARCHAR2(1000)		NOT NULL,
	"STAR"	NUMBER		NOT NULL,
	"ENROLL_DATE"	TIMESTAMP	DEFAULT SYSDATE	NOT NULL,
	"DELETE_YN"	CHAR(1)	DEFAULT 'N' CHECK(DELETE_YN IN ('Y' , 'N'))	NOT NULL,
	"MODIFY_DATE"	TIMESTAMP	DEFAULT SYSDATE	NOT NULL,
    --01 09 추가
    "PAYMENT_NO" NUMBER NULL
);

CREATE TABLE "MENTORING_CATEGORY" (
	"NO"	NUMBER		NOT NULL,
	"NAME"	VARCHAR2(100)		NOT NULL
);

CREATE TABLE "FREE_BOARD" (
	"NO"	NUMBER		NOT NULL,
	"CATE_NO"	NUMBER		NOT NULL,
	"WRITER"	NUMBER		NOT NULL,
	"TITLE"	VARCHAR2(1000)		NOT NULL,
	"CONTENT"	CLOB		NOT NULL,
	"ENROLL_DATE"	TIMESTAMP	DEFAULT SYSDATE	NOT NULL,
	"DELETE_YN"	CHAR(1)	DEFAULT 'N' CHECK(DELETE_YN IN ('Y' , 'N'))	NOT NULL,
	"MODIFY_DATE"	TIMESTAMP	DEFAULT SYSDATE	NOT NULL,
	"HIT"	NUMBER	DEFAULT 0	NOT NULL
);

CREATE TABLE "FREE_BOARD_CMT" (
	"NO"	NUMBER		NOT NULL,
	"BOARD_NO"	NUMBER		NOT NULL,
	"WRITER"	NUMBER		NOT NULL,
	"CONTENT"	CLOB		NOT NULL,
	"ENROLL_DATE"	TIMESTAMP	DEFAULT SYSDATE	NOT NULL,
	"DELETE_YN"	CHAR(1)	DEFAULT 'N' CHECK(DELETE_YN IN ('Y' , 'N'))	NOT NULL,
	"MODIFY_DATE"	TIMESTAMP	DEFAULT SYSDATE	NOT NULL,
	"DEPTH"	NUMBER		DEFAULT 0,
	"GROUP"	NUMBER
);

CREATE TABLE "FREE_BOARD_IMG" (
	"NO"	NUMBER		NOT NULL,
	"BOARD_NO"	NUMBER		NOT NULL,
	"IMG_PATH"	VARCHAR2(1000)		NOT NULL,
	"ENROLL_DATE"	TIMESTAMP	DEFAULT SYSDATE	NOT NULL,
	"THUMB_YN"	CHAR(1)	DEFAULT 'N' CHECK(THUMB_YN IN ('Y' , 'N'))	NOT NULL
);

CREATE TABLE "FREE_BOARD_LIKE_HATE" (
	"M_NO"	NUMBER		NOT NULL,
	"BOARD_NO"	NUMBER		NOT NULL,
	"STATUS"	CHAR(1)		NOT NULL
);

CREATE TABLE "FREE_BOARD_SCRAP" (
	"M_NO"	NUMBER		NOT NULL,
	"BOARD_NO"	NUMBER		NOT NULL
);

CREATE TABLE "FREE_BOARD_CATEGORY" (
	"NO"	NUMBER		NOT NULL,
	"NAME"	VARCHAR2(100)		NOT NULL
);

CREATE TABLE "GROUP_LIKE_HATE" (
	"M_NO"	NUMBER		NOT NULL,
	"G_NO"	NUMBER		NOT NULL,
	"STATUS"	CHAR(1)		NOT NULL
);

CREATE TABLE "MG_LIKE_HATE" (
	"M_NO"	NUMBER		NOT NULL,
	"MG_NO"	NUMBER		NOT NULL,
	"STATUS"	CHAR(1)		NOT NULL
);

CREATE TABLE "GROUP_CMT_LIKE_HATE" (
	"M_NO"	NUMBER		NOT NULL,
	"CMT_NO"	NUMBER		NOT NULL,
	"STATUS"	CHAR(1)		NULL
);

CREATE TABLE "MG_CMT_LIKE_HATE" (
	"M_NO"	NUMBER		NOT NULL,
	"CMT_NO"	NUMBER		NOT NULL,
	"STATUS"	CHAR(1)		NULL
);

CREATE TABLE "FREE_BOARD_CMT_LIKE_HATE" (
	"M_NO"	NUMBER		NOT NULL,
	"CMT_NO"	NUMBER		NOT NULL,
	"STATUS"	CHAR(1)		NOT NULL
);

CREATE TABLE "K_CMT_LIKE_HATE" (
	"M_NO"	NUMBER		NOT NULL,
	"A_NO"	NUMBER		NOT NULL,
	"STATUS"	CHAR(1)		NOT NULL
);

CREATE TABLE "GROUP_TECH_STACK" (
	"G_NO"	NUMBER		NOT NULL,
	"TECH_STACK_NO"	NUMBER		NOT NULL
);

CREATE TABLE "MEMBER_STACK" (
	"M_NO"	NUMBER		NOT NULL,
	"TECH_STACK_NO"	NUMBER		NOT NULL
);

CREATE TABLE "TAG" (
	"NO"	NUMBER		NOT NULL,
	"NAME"	VARCHAR(300)		NULL
);

CREATE TABLE "MG_TAG" (
	"MG_NO"	NUMBER		NOT NULL,
	"TAG_NO"	NUMBER		NOT NULL
);

CREATE TABLE "GROUP_TAG" (
	"GROUP_NO"	NUMBER		NOT NULL,
	"TAG_NO"	NUMBER		NOT NULL
);

CREATE TABLE "KNOWLEDGE_TAG" (
	"A_NO"	NUMBER		NOT NULL,
	"TAG_NO"	NUMBER		NOT NULL
);

CREATE TABLE "GROUP_BOARD" (
	"NO"	NUMBER		NOT NULL,
	"CATE_NO"	NUMBER		NOT NULL,
	"WRITER"	NUMBER		NOT NULL,
	"TITLE"	VARCHAR2(1000)		NOT NULL,
	"CONTENT"	CLOB		NOT NULL,
	"ENROLL_DATE"	TIMESTAMP	DEFAULT SYSDATE	NOT NULL,
	"DELETE_YN"	CHAR(1)	DEFAULT 'N' CHECK(DELETE_YN IN ('Y' , 'N'))	NOT NULL,
	"MODIFY_DATE"	TIMESTAMP	DEFAULT SYSDATE	NOT NULL,
	"HIT"	NUMBER	DEFAULT '0'	NOT NULL
);

CREATE TABLE "GROUP_BOARD_CMT" (
	"NO"	NUMBER		NOT NULL,
	"G_BOARD_NO"	NUMBER		NOT NULL,
	"WRITER"	NUMBER		NOT NULL,
	"CONTENT"	VARCHAR2(4000)		NOT NULL,
	"ENROLL_DATE"	TIMESTAMP	DEFAULT SYSDATE	NOT NULL,
	"DELETE_YN"	CHAR(1)	DEFAULT 'N' CHECK(DELETE_YN IN ('Y' , 'N'))	NOT NULL,
	"MODIFY_DATE"	TIMESTAMP	DEFAULT SYSDATE	NOT NULL,
	"DEPTH"	NUMBER		NOT NULL,
	"GROUP"	NUMBER		NOT NULL
);

CREATE TABLE "GROUP_BOARD_IMG" (
	"NO"	NUMBER		NOT NULL,
	"G_BOARD_NO"	NUMBER		NOT NULL,
	"IMG_PATH"	VARCHAR2(1000)		NOT NULL,
	"ENROLL_DATE"	TIMESTAMP	DEFAULT SYSDATE	NOT NULL,
	"THUMB_YN"	CHAR(1)	DEFAULT 'N' CHECK(THUMB_YN IN ('Y' , 'N'))	NOT NULL
);

CREATE TABLE "GROUP_BOARD_CATEGORY" (
	"NO"	NUMBER		NOT NULL,
	"G_NO"	NUMBER		NOT NULL,
	"NAME"	VARCHAR2(100)		NOT NULL,
	"DELETE_YN"	CHAR(1)		NOT NULL
);

CREATE TABLE "JOB_CATEGORY" (
	"NO"	NUMBER		NOT NULL,
	"NAME"	VARCHAR(1000)		NOT NULL
);

CREATE TABLE "NOTICE_ADMIN" (
	"CATE_NO"	NUMBER		NOT NULL,
	"COUNT"	NUMBER		NULL
);

CREATE TABLE "VISITOR" (
    "NO"	NUMBER		NOT NULL,
	"IP"	VARCHAR2(100)		NOT NULL,
	"ENROLL_DATE"	TIMESTAMP		NOT NULL,
	"REFER"	VARCHAR2(300)		NULL,
	"AGENT"	VARCHAR2(400)       NOT NULL
);

CREATE TABLE "PAGE_VIEW" (
    "NO"	NUMBER		NOT NULL,
	"IP"	VARCHAR2(100)		NOT NULL,
	"ENROLL_DATE"	TIMESTAMP		NOT NULL,
	"REFER"	VARCHAR2(300)		NULL,
	"AGENT"	VARCHAR2(400)       NOT NULL
);

ALTER TABLE "MEMBER" ADD CONSTRAINT "PK_MEMBER" PRIMARY KEY (
	"NO"
);

ALTER TABLE "MEMBER_GRADE" ADD CONSTRAINT "PK_MEMBER_GRADE" PRIMARY KEY (
	"NO"
);

ALTER TABLE "ALARM" ADD CONSTRAINT "PK_ALARM" PRIMARY KEY (
	"NO"
);

ALTER TABLE "FOLLOW" ADD CONSTRAINT "PK_FOLLOW" PRIMARY KEY (
	"NO"
);

ALTER TABLE "ALARM_TYPE" ADD CONSTRAINT "PK_ALARM_TYPE" PRIMARY KEY (
	"NO"
);

ALTER TABLE "MEMBER_ITEM" ADD CONSTRAINT "PK_MEMBER_ITEM" PRIMARY KEY (
	"M_NO",
	"ITEM_NO"
);

ALTER TABLE "MEMBER_BADGE" ADD CONSTRAINT "PK_MEMBER_BADGE" PRIMARY KEY (
	"M_NO",
	"BADGE_NO"
);

ALTER TABLE "DM" ADD CONSTRAINT "PK_DM" PRIMARY KEY (
	"NO"
);

ALTER TABLE "DM_MASSAGE" ADD CONSTRAINT "PK_DM_MASSAGE" PRIMARY KEY (
	"NO"
);

-- 테이블명 RECRUIT_GROUP 으로 수정 (22-12-21)
ALTER TABLE "RECRUIT_GROUP" ADD CONSTRAINT "PK_RECRUIT_GROUP" PRIMARY KEY (
	"NO"
);

ALTER TABLE "NOTICE" ADD CONSTRAINT "PK_NOTICE" PRIMARY KEY (
	"NO"
);

ALTER TABLE "KNOWLEDGE_QUESTION" ADD CONSTRAINT "PK_KNOWLEDGE_QUESTION" PRIMARY KEY (
	"NO"
);

ALTER TABLE "MENTOR" ADD CONSTRAINT "PK_MENTOR" PRIMARY KEY (
	"NO"
);

ALTER TABLE "RECRUIT_QUESTION" ADD CONSTRAINT "PK_RECRUIT_QUESTION" PRIMARY KEY (
	"NO"
);

ALTER TABLE "NOTICE_CMT" ADD CONSTRAINT "PK_NOTICE_CMT" PRIMARY KEY (
	"NO"
);

ALTER TABLE "GROUP_CMT" ADD CONSTRAINT "PK_GROUP_CMT" PRIMARY KEY (
	"NO"
);

ALTER TABLE "NOTICE_FILE" ADD CONSTRAINT "PK_NOTICE_FILE" PRIMARY KEY (
	"NO"
);

ALTER TABLE "GROUP_IMG" ADD CONSTRAINT "PK_GROUP_IMG" PRIMARY KEY (
	"NO"
);

ALTER TABLE "FAQ" ADD CONSTRAINT "PK_FAQ" PRIMARY KEY (
	"NO"
);

ALTER TABLE "GROUP_SCRAP" ADD CONSTRAINT "PK_GROUP_SCRAP" PRIMARY KEY (
	"M_NO",
	"G_NO"
);

ALTER TABLE "TECH_STACK" ADD CONSTRAINT "PK_TECH_STACK" PRIMARY KEY (
	"NO"
);

-- 테이블 추가 (22-12-22)
ALTER TABLE "TECH_STACK_TYPE" ADD CONSTRAINT "PK_TECH_STACK_TYPE" PRIMARY KEY (
	"NO"
);

ALTER TABLE "FAQ_IMG" ADD CONSTRAINT "PK_FAQ_IMG" PRIMARY KEY (
	"NO"
);

ALTER TABLE "KNOWLEDGE_ANSWER" ADD CONSTRAINT "PK_KNOWLEDGE_ANSWER" PRIMARY KEY (
	"NO"
);

ALTER TABLE "RECRUIT_LIST" ADD CONSTRAINT "PK_RECRUIT_LIST" PRIMARY KEY (
	"NO"
);

ALTER TABLE "RECRUIT_REPLY" ADD CONSTRAINT "PK_RECRUIT_REPLY" PRIMARY KEY (
	"NO"
);

ALTER TABLE "QUESTION_BOARD" ADD CONSTRAINT "PK_QUESTION_BOARD" PRIMARY KEY (
	"NO"
);

ALTER TABLE "QUESTION_BOARD_CMT" ADD CONSTRAINT "PK_QUESTION_BOARD_CMT" PRIMARY KEY (
	"NO"
);

ALTER TABLE "QUESTION_BOARD_IMG" ADD CONSTRAINT "PK_QUESTION_BOARD_IMG" PRIMARY KEY (
	"NO"
);

ALTER TABLE "COMMON_CATEGORY" ADD CONSTRAINT "PK_COMMON_CATEGORY" PRIMARY KEY (
	"NO"
);

ALTER TABLE "BADGE" ADD CONSTRAINT "PK_BADGE" PRIMARY KEY (
	"NO"
);

ALTER TABLE "ITEM" ADD CONSTRAINT "PK_ITEM" PRIMARY KEY (
	"NO"
);

ALTER TABLE "ADMIN" ADD CONSTRAINT "PK_ADMIN" PRIMARY KEY (
	"NO"
);

ALTER TABLE "KNOWLEDGE_IMG" ADD CONSTRAINT "PK_KNOWLEDGE_IMG" PRIMARY KEY (
	"NO"
);

ALTER TABLE "KNOWLEDGE_LIKE_HATE" ADD CONSTRAINT "PK_KNOWLEDGE_LIKE_HATE" PRIMARY KEY (
	"NO",
	"M_NO"
);

ALTER TABLE "KNOWLEDGE_SCRAP" ADD CONSTRAINT "PK_KNOWLEDGE_SCRAP" PRIMARY KEY (
	"Q_NO",
	"M_NO"
);

ALTER TABLE "KNOWLEDGE_CATEGORY" ADD CONSTRAINT "PK_KNOWLEDGE_CATEGORY" PRIMARY KEY (
	"NO"
);

ALTER TABLE "MAKE_GRASS" ADD CONSTRAINT "PK_MAKE_GRASS" PRIMARY KEY (
	"NO"
);

ALTER TABLE "MENTORING_SCHEDULE" ADD CONSTRAINT "PK_MENTORING_SCHEDULE" PRIMARY KEY (
	"NO"
);

ALTER TABLE "ADMIN_LOGIN" ADD CONSTRAINT "PK_ADMIN_LOGIN" PRIMARY KEY (
	"NO"
);

ALTER TABLE "BANNER" ADD CONSTRAINT "PK_BANNER" PRIMARY KEY (
	"NO"
);

ALTER TABLE "MG_CMT" ADD CONSTRAINT "PK_MG_CMT" PRIMARY KEY (
	"NO"
);

ALTER TABLE "MG_IMG" ADD CONSTRAINT "PK_MG_IMG" PRIMARY KEY (
	"NO"
);

ALTER TABLE "MENTORING_PAYMENT" ADD CONSTRAINT "PK_MENTORING_PAYMENT" PRIMARY KEY (
	"NO"
);

ALTER TABLE "POPUP" ADD CONSTRAINT "PK_POPUP" PRIMARY KEY (
	"NO"
);

ALTER TABLE "MG_SCRAP" ADD CONSTRAINT "PK_MG_SCRAP" PRIMARY KEY (
	"NO",
	"M_NO"
);

ALTER TABLE "GROUP_TYPE" ADD CONSTRAINT "PK_GROUP_TYPE" PRIMARY KEY (
	"NO"
);

ALTER TABLE "GROUP_WAY" ADD CONSTRAINT "PK_GROUP_WAY" PRIMARY KEY (
	"NO"
);

ALTER TABLE "GROUP_PERIOD" ADD CONSTRAINT "PK_GROUP_PERIOD" PRIMARY KEY (
	"NO"
);

ALTER TABLE "MENTORING_REVIEW" ADD CONSTRAINT "PK_MENTORING_REVIEW" PRIMARY KEY (
	"NO"
);

ALTER TABLE "MENTORING_CATEGORY" ADD CONSTRAINT "PK_MENTORING_CATEGORY" PRIMARY KEY (
	"NO"
);

ALTER TABLE "FREE_BOARD" ADD CONSTRAINT "PK_FREE_BOARD" PRIMARY KEY (
	"NO"
);

ALTER TABLE "FREE_BOARD_CMT" ADD CONSTRAINT "PK_FREE_BOARD_CMT" PRIMARY KEY (
	"NO"
);

ALTER TABLE "FREE_BOARD_IMG" ADD CONSTRAINT "PK_FREE_BOARD_IMG" PRIMARY KEY (
	"NO"
);

ALTER TABLE "FREE_BOARD_LIKE_HATE" ADD CONSTRAINT "PK_FREE_BOARD_LIKE_HATE" PRIMARY KEY (
	"M_NO",
	"BOARD_NO"
);

ALTER TABLE "FREE_BOARD_SCRAP" ADD CONSTRAINT "PK_FREE_BOARD_SCRAP" PRIMARY KEY (
	"M_NO",
	"BOARD_NO"
);

ALTER TABLE "FREE_BOARD_CATEGORY" ADD CONSTRAINT "PK_FREE_BOARD_CATEGORY" PRIMARY KEY (
	"NO"
);

ALTER TABLE "GROUP_LIKE_HATE" ADD CONSTRAINT "PK_GROUP_LIKE_HATE" PRIMARY KEY (
	"M_NO",
	"G_NO"
);

ALTER TABLE "MG_LIKE_HATE" ADD CONSTRAINT "PK_MG_LIKE_HATE" PRIMARY KEY (
	"M_NO",
	"MG_NO"
);

ALTER TABLE "GROUP_CMT_LIKE_HATE" ADD CONSTRAINT "PK_GROUP_CMT_LIKE_HATE" PRIMARY KEY (
	"M_NO",
	"CMT_NO"
);

ALTER TABLE "MG_CMT_LIKE_HATE" ADD CONSTRAINT "PK_MG_CMT_LIKE_HATE" PRIMARY KEY (
	"M_NO",
	"CMT_NO"
);

ALTER TABLE "FREE_BOARD_CMT_LIKE_HATE" ADD CONSTRAINT "PK_FREE_BOARD_CMT_LIKE_HATE" PRIMARY KEY (
	"M_NO",
	"CMT_NO"
);

ALTER TABLE "K_CMT_LIKE_HATE" ADD CONSTRAINT "PK_K_CMT_LIKE_HATE" PRIMARY KEY (
	"M_NO",
	"A_NO"
);

ALTER TABLE "GROUP_TECH_STACK" ADD CONSTRAINT "PK_GROUP_TECH_STACK" PRIMARY KEY (
	"G_NO",
	"TECH_STACK_NO"
);

ALTER TABLE "MEMBER_STACK" ADD CONSTRAINT "PK_MEMBER_STACK" PRIMARY KEY (
	"M_NO",
	"TECH_STACK_NO"
);

ALTER TABLE "TAG" ADD CONSTRAINT "PK_TAG" PRIMARY KEY (
	"NO"
);

ALTER TABLE "MG_TAG" ADD CONSTRAINT "PK_MG_TAG" PRIMARY KEY (
	"MG_NO",
	"TAG_NO"
);

ALTER TABLE "GROUP_TAG" ADD CONSTRAINT "PK_GROUP_TAG" PRIMARY KEY (
	"GROUP_NO",
	"TAG_NO"
);

ALTER TABLE "KNOWLEDGE_TAG" ADD CONSTRAINT "PK_KNOWLEDGE_TAG" PRIMARY KEY (
	"A_NO",
	"TAG_NO"
);

ALTER TABLE "GROUP_BOARD" ADD CONSTRAINT "PK_GROUP_BOARD" PRIMARY KEY (
	"NO"
);

ALTER TABLE "GROUP_BOARD_CMT" ADD CONSTRAINT "PK_GROUP_BOARD_CMT" PRIMARY KEY (
	"NO"
);

ALTER TABLE "GROUP_BOARD_IMG" ADD CONSTRAINT "PK_GROUP_BOARD_IMG" PRIMARY KEY (
	"NO"
);

ALTER TABLE "GROUP_BOARD_CATEGORY" ADD CONSTRAINT "PK_GROUP_BOARD_CATEGORY" PRIMARY KEY (
	"NO"
);

ALTER TABLE "JOB_CATEGORY" ADD CONSTRAINT "PK_JOB_CATEGORY" PRIMARY KEY (
	"NO"
);

ALTER TABLE "VISITOR" ADD CONSTRAINT "PK_VISITOR" PRIMARY KEY (
	"NO"
);

ALTER TABLE "PAGE_VIEW" ADD CONSTRAINT "PK_PAGE_VIEW" PRIMARY KEY (
	"NO"
);

ALTER TABLE "ALARM" ADD CONSTRAINT "FK_MEMBER_TO_ALARM_1" FOREIGN KEY (
	"SEND_M_NO"
)
REFERENCES "MEMBER" (
	"NO"
);

ALTER TABLE "ALARM" ADD CONSTRAINT "FK_MEMBER_TO_ALARM_2" FOREIGN KEY (
	"RECE_M_NO"
)
REFERENCES "MEMBER" (
	"NO"
);

ALTER TABLE "ALARM" ADD CONSTRAINT "FK_ALARM_TYPE_TO_ALARM_1" FOREIGN KEY (
	"ALARM_TYPE_NO"
)
REFERENCES "ALARM_TYPE" (
	"NO"
);

ALTER TABLE "FOLLOW" ADD CONSTRAINT "FK_MEMBER_TO_FOLLOW_1" FOREIGN KEY (
	"FOLLOWING_NO"
)
REFERENCES "MEMBER" (
	"NO"
);

ALTER TABLE "FOLLOW" ADD CONSTRAINT "FK_MEMBER_TO_FOLLOW_2" FOREIGN KEY (
	"FOLLOWER_NO"
)
REFERENCES "MEMBER" (
	"NO"
);

ALTER TABLE "MEMBER_ITEM" ADD CONSTRAINT "FK_MEMBER_TO_MEMBER_ITEM_1" FOREIGN KEY (
	"M_NO"
)
REFERENCES "MEMBER" (
	"NO"
);

ALTER TABLE "MEMBER_ITEM" ADD CONSTRAINT "FK_ITEM_TO_MEMBER_ITEM_1" FOREIGN KEY (
	"ITEM_NO"
)
REFERENCES "ITEM" (
	"NO"
);

ALTER TABLE "MEMBER_BADGE" ADD CONSTRAINT "FK_MEMBER_TO_MEMBER_BADGE_1" FOREIGN KEY (
	"M_NO"
)
REFERENCES "MEMBER" (
	"NO"
);

ALTER TABLE "MEMBER_BADGE" ADD CONSTRAINT "FK_BADGE_TO_MEMBER_BADGE_1" FOREIGN KEY (
	"BADGE_NO"
)
REFERENCES "BADGE" (
	"NO"
);

ALTER TABLE "DM" ADD CONSTRAINT "FK_MEMBER_TO_DM_1" FOREIGN KEY (
	"SEND_M_NO"
)
REFERENCES "MEMBER" (
	"NO"
);

ALTER TABLE "DM" ADD CONSTRAINT "FK_MEMBER_TO_DM_2" FOREIGN KEY (
	"RECE_M_NO"
)
REFERENCES "MEMBER" (
	"NO"
);

ALTER TABLE "DM_MASSAGE" ADD CONSTRAINT "FK_DM_TO_DM_MASSAGE_1" FOREIGN KEY (
	"DM_NO"
)
REFERENCES "DM" (
	"NO"
);

--테이블명 RECRUIT_GROUP 으로 수정 (22-12-21)
ALTER TABLE "RECRUIT_GROUP" ADD CONSTRAINT "FK_MEMBER_TO_RECRUIT_GROUP_1" FOREIGN KEY (
	"WRITER"
)
REFERENCES "MEMBER" (
	"NO"
);

--테이블명 RECRUIT_GROUP 으로 수정 (22-12-21)
ALTER TABLE "RECRUIT_GROUP" ADD CONSTRAINT "FK_GROUP_TYPE_TO_RECRUIT_GROUP_1" FOREIGN KEY (
	"G_TYPE_NO"
)
REFERENCES "GROUP_TYPE" (
	"NO"
);

--테이블명 RECRUIT_GROUP 으로 수정 (22-12-21)
ALTER TABLE "RECRUIT_GROUP" ADD CONSTRAINT "FK_GROUP_WAY_TO_RECRUIT_GROUP_1" FOREIGN KEY (
	"G_WAY_NO"
)
REFERENCES "GROUP_WAY" (
	"NO"
);

--테이블명 RECRUIT_GROUP 으로 수정 (22-12-21)
ALTER TABLE "RECRUIT_GROUP" ADD CONSTRAINT "FK_GROUP_PERIOD_TO_RECRUIT_GROUP_1" FOREIGN KEY (
	"G_PERIOD_NO"
)
REFERENCES "GROUP_PERIOD" (
	"NO"
);

ALTER TABLE "NOTICE" ADD CONSTRAINT "FK_COMMON_CATEGORY_TO_NOTICE_1" FOREIGN KEY (
	"CATE_NO"
)
REFERENCES "COMMON_CATEGORY" (
	"NO"
);

ALTER TABLE "NOTICE" ADD CONSTRAINT "FK_MEMBER_TO_NOTICE_1" FOREIGN KEY (
	"WRITER"
)
REFERENCES "MEMBER" (
	"NO"
);

ALTER TABLE "KNOWLEDGE_QUESTION" ADD CONSTRAINT "FK_MEMBER_TO_KNOWLEDGE_QUESTION_1" FOREIGN KEY (
	"WRITER"
)
REFERENCES "MEMBER" (
	"NO"
);

ALTER TABLE "KNOWLEDGE_QUESTION" ADD CONSTRAINT "FK_KNOWLEDGE_CATEGORY_TO_KNOWLEDGE_QUESTION_1" FOREIGN KEY (
	"CATE_NO"
)
REFERENCES "KNOWLEDGE_CATEGORY" (
	"NO"
);

ALTER TABLE "MENTOR" ADD CONSTRAINT "FK_MEMBER_TO_MENTOR_1" FOREIGN KEY (
	"WRITER"
)
REFERENCES "MEMBER" (
	"NO"
);

ALTER TABLE "MENTOR" ADD CONSTRAINT "FK_MENTORING_CATEGORY_TO_MENTOR_1" FOREIGN KEY (
	"CATE_NO"
)
REFERENCES "MENTORING_CATEGORY" (
	"NO"
);

ALTER TABLE "MENTOR" ADD CONSTRAINT "FK_JOB_CATEGORY_TO_MENTOR_1" FOREIGN KEY (
	"JOB"
)
REFERENCES "JOB_CATEGORY" (
	"NO"
);

--테이블명 RECRUIT_GROUP 으로 수정 (22-12-21)
ALTER TABLE "RECRUIT_QUESTION" ADD CONSTRAINT "FK_RECRUIT_GROUP_TO_RECRUIT_QUESTION_1" FOREIGN KEY (
	"G_NO"
)
REFERENCES "RECRUIT_GROUP" (
	"NO"
);

ALTER TABLE "NOTICE_CMT" ADD CONSTRAINT "FK_NOTICE_TO_NOTICE_CMT_1" FOREIGN KEY (
	"N_NO"
)
REFERENCES "NOTICE" (
	"NO"
);

ALTER TABLE "NOTICE_CMT" ADD CONSTRAINT "FK_MEMBER_TO_NOTICE_CMT_1" FOREIGN KEY (
	"WRITER"
)
REFERENCES "MEMBER" (
	"NO"
);

--RECRUIT_GROUP 으로 이름 수정 (22-12-23)
ALTER TABLE "GROUP_CMT" ADD CONSTRAINT "FK_RECRUIT_GROUP_TO_GROUP_CMT_1" FOREIGN KEY (
	"G_NO"
)
REFERENCES "RECRUIT_GROUP" (
	"NO"
);

ALTER TABLE "GROUP_CMT" ADD CONSTRAINT "FK_MEMBER_TO_GROUP_CMT_1" FOREIGN KEY (
	"WRITER"
)
REFERENCES "MEMBER" (
	"NO"
);

ALTER TABLE "NOTICE_FILE" ADD CONSTRAINT "FK_NOTICE_TO_NOTICE_FILE_1" FOREIGN KEY (
	"N_NO"
)
REFERENCES "NOTICE" (
	"NO"
);

-- RECRUIT_GROUP으로 이름 수정 (22-12-23)
ALTER TABLE "GROUP_IMG" ADD CONSTRAINT "FK_RECRUIT_GROUP_TO_GROUP_IMG_1" FOREIGN KEY (
	"G_NO"
)
REFERENCES "RECRUIT_GROUP" (
	"NO"
);

ALTER TABLE "FAQ" ADD CONSTRAINT "FK_COMMON_CATEGORY_TO_FAQ_1" FOREIGN KEY (
	"CATE_NO"
)
REFERENCES "COMMON_CATEGORY" (
	"NO"
);

ALTER TABLE "FAQ" ADD CONSTRAINT "FK_MEMBER_TO_FAQ_1" FOREIGN KEY (
	"WRITER"
)
REFERENCES "MEMBER" (
	"NO"
);

ALTER TABLE "GROUP_SCRAP" ADD CONSTRAINT "FK_MEMBER_TO_GROUP_SCRAP_1" FOREIGN KEY (
	"M_NO"
)
REFERENCES "MEMBER" (
	"NO"
);

-- 테이블명 RECRUIT_GROUP으로 수정 (22-12-21)
ALTER TABLE "GROUP_SCRAP" ADD CONSTRAINT "FK_RECRUIT_GROUP_TO_GROUP_SCRAP_1" FOREIGN KEY (
	"G_NO"
)
REFERENCES "RECRUIT_GROUP" (
	"NO"
);

ALTER TABLE "FAQ_IMG" ADD CONSTRAINT "FK_FAQ_TO_FAQ_IMG_1" FOREIGN KEY (
	"F_NO"
)
REFERENCES "FAQ" (
	"NO"
);

ALTER TABLE "KNOWLEDGE_ANSWER" ADD CONSTRAINT "FK_KNOWLEDGE_QUESTION_TO_KNOWLEDGE_ANSWER_1" FOREIGN KEY (
	"Q_NO"
)
REFERENCES "KNOWLEDGE_QUESTION" (
	"NO"
);

ALTER TABLE "KNOWLEDGE_ANSWER" ADD CONSTRAINT "FK_MEMBER_TO_KNOWLEDGE_ANSWER_1" FOREIGN KEY (
	"WRITER"
)
REFERENCES "MEMBER" (
	"NO"
);

-- 테이블명 RECRUIT_GROUP으로 수정 (22-12-21)
ALTER TABLE "RECRUIT_LIST" ADD CONSTRAINT "FK_RECRUIT_GROUP_TO_RECRUIT_LIST_1" FOREIGN KEY (
	"G_NO"
)
REFERENCES "RECRUIT_GROUP" (
	"NO"
);

ALTER TABLE "RECRUIT_LIST" ADD CONSTRAINT "FK_MEMBER_TO_RECRUIT_LIST_1" FOREIGN KEY (
	"M_NO"
)
REFERENCES "MEMBER" (
	"NO"
);

ALTER TABLE "RECRUIT_REPLY" ADD CONSTRAINT "FK_RECRUIT_QUESTION_TO_RECRUIT_REPLY_1" FOREIGN KEY (
	"RECRUIT_QUESTION_NO"
)
REFERENCES "RECRUIT_QUESTION" (
	"NO"
);

ALTER TABLE "RECRUIT_REPLY" ADD CONSTRAINT "FK_RECRUIT_LIST_TO_RECRUIT_REPLY_1" FOREIGN KEY (
	"RECRUIT_LIST_NO"
)
REFERENCES "RECRUIT_LIST" (
	"NO"
);

ALTER TABLE "QUESTION_BOARD" ADD CONSTRAINT "FK_COMMON_CATEGORY_TO_QUESTION_BOARD_1" FOREIGN KEY (
	"CATE_NO"
)
REFERENCES "COMMON_CATEGORY" (
	"NO"
);

ALTER TABLE "QUESTION_BOARD" ADD CONSTRAINT "FK_MEMBER_TO_QUESTION_BOARD_1" FOREIGN KEY (
	"WRITER"
)
REFERENCES "MEMBER" (
	"NO"
);

ALTER TABLE "QUESTION_BOARD_CMT" ADD CONSTRAINT "FK_QUESTION_BOARD_TO_QUESTION_BOARD_CMT_1" FOREIGN KEY (
	"Q_NO"
)
REFERENCES "QUESTION_BOARD" (
	"NO"
);

ALTER TABLE "QUESTION_BOARD_CMT" ADD CONSTRAINT "FK_MEMBER_TO_QUESTION_BOARD_CMT_1" FOREIGN KEY (
	"WRITER"
)
REFERENCES "MEMBER" (
	"NO"
);

ALTER TABLE "QUESTION_BOARD_IMG" ADD CONSTRAINT "FK_QUESTION_BOARD_TO_QUESTION_BOARD_IMG_1" FOREIGN KEY (
	"Q_NO"
)
REFERENCES "QUESTION_BOARD" (
	"NO"
);

ALTER TABLE "KNOWLEDGE_IMG" ADD CONSTRAINT "FK_KNOWLEDGE_QUESTION_TO_KNOWLEDGE_IMG_1" FOREIGN KEY (
	"Q_NO"
)
REFERENCES "KNOWLEDGE_QUESTION" (
	"NO"
);

ALTER TABLE "KNOWLEDGE_LIKE_HATE" ADD CONSTRAINT "FK_KNOWLEDGE_QUESTION_TO_KNOWLEDGE_LIKE_HATE_1" FOREIGN KEY (
	"NO"
)
REFERENCES "KNOWLEDGE_QUESTION" (
	"NO"
);

ALTER TABLE "KNOWLEDGE_LIKE_HATE" ADD CONSTRAINT "FK_MEMBER_TO_KNOWLEDGE_LIKE_HATE_1" FOREIGN KEY (
	"M_NO"
)
REFERENCES "MEMBER" (
	"NO"
);

ALTER TABLE "KNOWLEDGE_SCRAP" ADD CONSTRAINT "FK_KNOWLEDGE_QUESTION_TO_KNOWLEDGE_SCRAP_1" FOREIGN KEY (
	"Q_NO"
)
REFERENCES "KNOWLEDGE_QUESTION" (
	"NO"
);

ALTER TABLE "KNOWLEDGE_SCRAP" ADD CONSTRAINT "FK_MEMBER_TO_KNOWLEDGE_SCRAP_1" FOREIGN KEY (
	"M_NO"
)
REFERENCES "MEMBER" (
	"NO"
);

ALTER TABLE "MAKE_GRASS" ADD CONSTRAINT "FK_MEMBER_TO_MAKE_GRASS_1" FOREIGN KEY (
	"WRITER"
)
REFERENCES "MEMBER" (
	"NO"
);

ALTER TABLE "MENTORING_SCHEDULE" ADD CONSTRAINT "FK_MENTOR_TO_MENTORING_SCHEDULE_1" FOREIGN KEY (
	"MENTOR_NO"
)
REFERENCES "MENTOR" (
	"NO"
);

ALTER TABLE "ADMIN_LOGIN" ADD CONSTRAINT "FK_ADMIN_TO_ADMIN_LOGIN_1" FOREIGN KEY (
	"A_NO"
)
REFERENCES "ADMIN" (
	"NO"
);

ALTER TABLE "MG_CMT" ADD CONSTRAINT "FK_MAKE_GRASS_TO_MG_CMT_1" FOREIGN KEY (
	"MG_NO"
)
REFERENCES "MAKE_GRASS" (
	"NO"
);

ALTER TABLE "MG_CMT" ADD CONSTRAINT "FK_MEMBER_TO_MG_CMT_1" FOREIGN KEY (
	"WRITER"
)
REFERENCES "MEMBER" (
	"NO"
);

ALTER TABLE "MG_IMG" ADD CONSTRAINT "FK_MAKE_GRASS_TO_MG_IMG_1" FOREIGN KEY (
	"MG_NO"
)
REFERENCES "MAKE_GRASS" (
	"NO"
);

ALTER TABLE "MENTORING_PAYMENT" ADD CONSTRAINT "FK_MENTOR_TO_MENTORING_PAYMENT_1" FOREIGN KEY (
	"MENTOR_NO"
)
REFERENCES "MENTOR" (
	"NO"
);

ALTER TABLE "MENTORING_PAYMENT" ADD CONSTRAINT "FK_MEMBER_TO_MENTORING_PAYMENT_1" FOREIGN KEY (
	"M_NO"
)
REFERENCES "MEMBER" (
	"NO"
);

ALTER TABLE "MG_SCRAP" ADD CONSTRAINT "FK_MAKE_GRASS_TO_MG_SCRAP_1" FOREIGN KEY (
	"NO"
)
REFERENCES "MAKE_GRASS" (
	"NO"
);

ALTER TABLE "MG_SCRAP" ADD CONSTRAINT "FK_MEMBER_TO_MG_SCRAP_1" FOREIGN KEY (
	"M_NO"
)
REFERENCES "MEMBER" (
	"NO"
);

ALTER TABLE "MENTORING_REVIEW" ADD CONSTRAINT "FK_MENTOR_TO_MENTORING_REVIEW_1" FOREIGN KEY (
	"MENTOR_NO"
)
REFERENCES "MENTOR" (
	"NO"
);

ALTER TABLE "MENTORING_REVIEW" ADD CONSTRAINT "FK_MEMBER_TO_MENTORING_REVIEW_1" FOREIGN KEY (
	"WRITER"
)
REFERENCES "MEMBER" (
	"NO"
);

ALTER TABLE "FREE_BOARD" ADD CONSTRAINT "FK_FREE_BOARD_CATEGORY_TO_FREE_BOARD_1" FOREIGN KEY (
	"CATE_NO"
)
REFERENCES "FREE_BOARD_CATEGORY" (
	"NO"
);

ALTER TABLE "FREE_BOARD" ADD CONSTRAINT "FK_MEMBER_TO_FREE_BOARD_1" FOREIGN KEY (
	"WRITER"
)
REFERENCES "MEMBER" (
	"NO"
);

ALTER TABLE "FREE_BOARD_CMT" ADD CONSTRAINT "FK_FREE_BOARD_TO_FREE_BOARD_CMT_1" FOREIGN KEY (
	"BOARD_NO"
)
REFERENCES "FREE_BOARD" (
	"NO"
);

ALTER TABLE "FREE_BOARD_CMT" ADD CONSTRAINT "FK_MEMBER_TO_FREE_BOARD_CMT_1" FOREIGN KEY (
	"WRITER"
)
REFERENCES "MEMBER" (
	"NO"
);

ALTER TABLE "FREE_BOARD_IMG" ADD CONSTRAINT "FK_FREE_BOARD_TO_FREE_BOARD_IMG_1" FOREIGN KEY (
	"BOARD_NO"
)
REFERENCES "FREE_BOARD" (
	"NO"
);

ALTER TABLE "FREE_BOARD_LIKE_HATE" ADD CONSTRAINT "FK_MEMBER_TO_FREE_BOARD_LIKE_HATE_1" FOREIGN KEY (
	"M_NO"
)
REFERENCES "MEMBER" (
	"NO"
);

ALTER TABLE "FREE_BOARD_LIKE_HATE" ADD CONSTRAINT "FK_FREE_BOARD_TO_FREE_BOARD_LIKE_HATE_1" FOREIGN KEY (
	"BOARD_NO"
)
REFERENCES "FREE_BOARD" (
	"NO"
);

ALTER TABLE "FREE_BOARD_SCRAP" ADD CONSTRAINT "FK_MEMBER_TO_FREE_BOARD_SCRAP_1" FOREIGN KEY (
	"M_NO"
)
REFERENCES "MEMBER" (
	"NO"
);

ALTER TABLE "FREE_BOARD_SCRAP" ADD CONSTRAINT "FK_FREE_BOARD_TO_FREE_BOARD_SCRAP_1" FOREIGN KEY (
	"BOARD_NO"
)
REFERENCES "FREE_BOARD" (
	"NO"
);

ALTER TABLE "GROUP_LIKE_HATE" ADD CONSTRAINT "FK_MEMBER_TO_GROUP_LIKE_HATE_1" FOREIGN KEY (
	"M_NO"
)
REFERENCES "MEMBER" (
	"NO"
);

-- 테이블명 RECRUIT_GROUP으로 수정 (22-12-21)
ALTER TABLE "GROUP_LIKE_HATE" ADD CONSTRAINT "FK_RECRUIT_GROUP_TO_GROUP_LIKE_HATE_1" FOREIGN KEY (
	"G_NO"
)
REFERENCES "RECRUIT_GROUP" (
	"NO"
);

ALTER TABLE "MG_LIKE_HATE" ADD CONSTRAINT "FK_MEMBER_TO_MG_LIKE_HATE_1" FOREIGN KEY (
	"M_NO"
)
REFERENCES "MEMBER" (
	"NO"
);

ALTER TABLE "MG_LIKE_HATE" ADD CONSTRAINT "FK_MAKE_GRASS_TO_MG_LIKE_HATE_1" FOREIGN KEY (
	"MG_NO"
)
REFERENCES "MAKE_GRASS" (
	"NO"
);

ALTER TABLE "GROUP_CMT_LIKE_HATE" ADD CONSTRAINT "FK_MEMBER_TO_GROUP_CMT_LIKE_HATE_1" FOREIGN KEY (
	"M_NO"
)
REFERENCES "MEMBER" (
	"NO"
);

ALTER TABLE "GROUP_CMT_LIKE_HATE" ADD CONSTRAINT "FK_GROUP_CMT_TO_GROUP_CMT_LIKE_HATE_1" FOREIGN KEY (
	"CMT_NO"
)
REFERENCES "GROUP_CMT" (
	"NO"
);

ALTER TABLE "MG_CMT_LIKE_HATE" ADD CONSTRAINT "FK_MEMBER_TO_MG_CMT_LIKE_HATE_1" FOREIGN KEY (
	"M_NO"
)
REFERENCES "MEMBER" (
	"NO"
);

ALTER TABLE "MG_CMT_LIKE_HATE" ADD CONSTRAINT "FK_MG_CMT_TO_MG_CMT_LIKE_HATE_1" FOREIGN KEY (
	"CMT_NO"
)
REFERENCES "MG_CMT" (
	"NO"
);

ALTER TABLE "FREE_BOARD_CMT_LIKE_HATE" ADD CONSTRAINT "FK_MEMBER_TO_FREE_BOARD_CMT_LIKE_HATE_1" FOREIGN KEY (
	"M_NO"
)
REFERENCES "MEMBER" (
	"NO"
);

ALTER TABLE "FREE_BOARD_CMT_LIKE_HATE" ADD CONSTRAINT "FK_FREE_BOARD_CMT_TO_FREE_BOARD_CMT_LIKE_HATE_1" FOREIGN KEY (
	"CMT_NO"
)
REFERENCES "FREE_BOARD_CMT" (
	"NO"
);

ALTER TABLE "K_CMT_LIKE_HATE" ADD CONSTRAINT "FK_MEMBER_TO_K_CMT_LIKE_HATE_1" FOREIGN KEY (
	"M_NO"
)
REFERENCES "MEMBER" (
	"NO"
);

ALTER TABLE "K_CMT_LIKE_HATE" ADD CONSTRAINT "FK_KNOWLEDGE_ANSWER_TO_K_CMT_LIKE_HATE_1" FOREIGN KEY (
	"A_NO"
)
REFERENCES "KNOWLEDGE_ANSWER" (
	"NO"
);

-- 테이블명 RECRUIT_GROUP으로 수정 (22-12-21)
ALTER TABLE "GROUP_TECH_STACK" ADD CONSTRAINT "FK_RECRUIT_GROUP_TO_GROUP_TECH_STACK_1" FOREIGN KEY (
	"G_NO"
)
REFERENCES "RECRUIT_GROUP" (
	"NO"
);

ALTER TABLE "GROUP_TECH_STACK" ADD CONSTRAINT "FK_TECH_STACK_TO_GROUP_TECH_STACK_1" FOREIGN KEY (
	"TECH_STACK_NO"
)
REFERENCES "TECH_STACK" (
	"NO"
);

-- 테이블 추가 (22-12-22)
ALTER TABLE "TECH_STACK" ADD CONSTRAINT "FK_TECH_STACK_TYPE_TO_TECH_STACK_1" FOREIGN KEY (
	"TYPE_NO"
)
REFERENCES "TECH_STACK_TYPE" (
	"NO"
);

ALTER TABLE "MEMBER_STACK" ADD CONSTRAINT "FK_MEMBER_TO_MEMBER_STACK_1" FOREIGN KEY (
	"M_NO"
)
REFERENCES "MEMBER" (
	"NO"
);

ALTER TABLE "MEMBER_STACK" ADD CONSTRAINT "FK_TECH_STACK_TO_MEMBER_STACK_1" FOREIGN KEY (
	"TECH_STACK_NO"
)
REFERENCES "TECH_STACK" (
	"NO"
);

ALTER TABLE "MG_TAG" ADD CONSTRAINT "FK_MAKE_GRASS_TO_MG_TAG_1" FOREIGN KEY (
	"MG_NO"
)
REFERENCES "MAKE_GRASS" (
	"NO"
);

ALTER TABLE "MG_TAG" ADD CONSTRAINT "FK_TAG_TO_MG_TAG_1" FOREIGN KEY (
	"TAG_NO"
)
REFERENCES "TAG" (
	"NO"
);

-- 테이블명 RECRUIT_GROUP으로 수정 (22-12-21)
ALTER TABLE "GROUP_TAG" ADD CONSTRAINT "FK_RECRUIT_GROUP_TO_GROUP_TAG_1" FOREIGN KEY (
	"GROUP_NO"
)
REFERENCES "RECRUIT_GROUP" (
	"NO"
);

ALTER TABLE "GROUP_TAG" ADD CONSTRAINT "FK_TAG_TO_GROUP_TAG_1" FOREIGN KEY (
	"TAG_NO"
)
REFERENCES "TAG" (
	"NO"
);

ALTER TABLE "KNOWLEDGE_TAG" ADD CONSTRAINT "FK_KNOWLEDGE_QUESTION_TO_KNOWLEDGE_TAG_1" FOREIGN KEY (
	"A_NO"
)
REFERENCES "KNOWLEDGE_QUESTION" (
	"NO"
);

ALTER TABLE "KNOWLEDGE_TAG" ADD CONSTRAINT "FK_TAG_TO_KNOWLEDGE_TAG_1" FOREIGN KEY (
	"TAG_NO"
)
REFERENCES "TAG" (
	"NO"
);

ALTER TABLE "GROUP_BOARD" ADD CONSTRAINT "FK_GROUP_BOARD_CATEGORY_TO_GROUP_BOARD_1" FOREIGN KEY (
	"CATE_NO"
)
REFERENCES "GROUP_BOARD_CATEGORY" (
	"NO"
);

ALTER TABLE "GROUP_BOARD" ADD CONSTRAINT "FK_MEMBER_TO_GROUP_BOARD_1" FOREIGN KEY (
	"WRITER"
)
REFERENCES "MEMBER" (
	"NO"
);

ALTER TABLE "GROUP_BOARD_CMT" ADD CONSTRAINT "FK_GROUP_BOARD_TO_GROUP_BOARD_CMT_1" FOREIGN KEY (
	"G_BOARD_NO"
)
REFERENCES "GROUP_BOARD" (
	"NO"
);

ALTER TABLE "GROUP_BOARD_CMT" ADD CONSTRAINT "FK_MEMBER_TO_GROUP_BOARD_CMT_1" FOREIGN KEY (
	"WRITER"
)
REFERENCES "MEMBER" (
	"NO"
);

ALTER TABLE "GROUP_BOARD_IMG" ADD CONSTRAINT "FK_GROUP_BOARD_TO_GROUP_BOARD_IMG_1" FOREIGN KEY (
	"G_BOARD_NO"
)
REFERENCES "GROUP_BOARD" (
	"NO"
);

--RECRUIT_GROUP으로 이름 수정 (22-12-23)
ALTER TABLE "GROUP_BOARD_CATEGORY" ADD CONSTRAINT "FK_RECRUIT_GROUP_TO_GROUP_BOARD_CATEGORY_1" FOREIGN KEY (
	"G_NO"
)
REFERENCES "RECRUIT_GROUP" (
	"NO"
);

ALTER TABLE "NOTICE_ADMIN" ADD CONSTRAINT "FK_COMMON_CATEGORY_TO_NOTICE_ADMIN_1" FOREIGN KEY (
	"CATE_NO"
)
REFERENCES "COMMON_CATEGORY" (
	"NO"
);


--시퀀스

--회원
CREATE SEQUENCE SEQ_MEMBER_NO NOCACHE NOCYCLE;

--회원 등급
CREATE SEQUENCE SEQ_MEMBER_GRADE_NO NOCACHE NOCYCLE;

--아이템 목록
CREATE SEQUENCE SEQ_ITEM_NO NOCACHE NOCYCLE;

--뱃지 유형
CREATE SEQUENCE SEQ_BADGE_NO NOCACHE NOCYCLE;

--알람 타입
CREATE SEQUENCE SEQ_ALARM_TYPE_NO NOCACHE NOCYCLE;

--알람 
CREATE SEQUENCE SEQ_ALARM_NO NOCACHE NOCYCLE;

--디엠 메세지
CREATE SEQUENCE SEQ_DM_MASSAGE_NO NOCACHE NOCYCLE;

--디엠 목록
CREATE SEQUENCE SEQ_DM_NO NOCACHE NOCYCLE;

--팔로우
CREATE SEQUENCE SEQ_FALLOW_NO NOCACHE NOCYCLE;

--기술스택
--오타 수정함 SEQ_TECK_STACK_NO -> SEQ_TECH_STACK_NO (22-12-21)
CREATE SEQUENCE SEQ_TECH_STACK_NO NOCACHE NOCYCLE;

--테이블 추가 (22-12-22)
--기술스택유형
CREATE SEQUENCE SEQ_TECH_STACK_TYPE_NO NOCACHE NOCYCLE;

-- 스터디/프로젝트 가입내역
CREATE SEQUENCE SEQ_RECRUIT_LIST_NO NOCACHE NOCYCLE;

-- 스터디/프로젝트 가입답변
CREATE SEQUENCE SEQ_RECRUIT_REPLY_NO NOCACHE NOCYCLE;

-- 스터디/프로젝트 가입질문
CREATE SEQUENCE SEQ_RECRUIT_QUESTION_NO NOCACHE NOCYCLE;

-- 스터디/프로젝트 진행기간
CREATE SEQUENCE SEQ_GROUP_PERIOD_NO NOCACHE NOCYCLE;

-- 스터디/프로젝트 진행방식
CREATE SEQUENCE SEQ_GROUP_WAY_NO NOCACHE NOCYCLE;

-- 스터디/프로젝트 모집유형
CREATE SEQUENCE SEQ_GROUP_TYPE_NO NOCACHE NOCYCLE;

-- 스터디/프로젝트 모임게시판 카테고리
CREATE SEQUENCE SEQ_GROUP_BOARD_CATEGORY_NO NOCACHE NOCYCLE;

-- 스터디/프로젝트 모집
-- 테이블명 수정 (22-12-21)
CREATE SEQUENCE SEQ_RECRUIT_GROUP_NO NOCACHE NOCYCLE;

-- 스터디/프로젝트 댓글
CREATE SEQUENCE SEQ_GROUP_CMT_NO NOCACHE NOCYCLE;

-- 스터디/프로젝트 첨부파일
CREATE SEQUENCE SEQ_GROUP_IMG_NO NOCACHE NOCYCLE;

-- 스터디/프로젝트 모임게시판 게시글
CREATE SEQUENCE SEQ_GROUP_BOARD_NO NOCACHE NOCYCLE;

-- 스터디/프로젝트 모임게시판 첨부파일
CREATE SEQUENCE SEQ_GROUP_BOARD_IMG_NO NOCACHE NOCYCLE;

-- 스터디/프로젝트 모임게시판 댓글
CREATE SEQUENCE SEQ_GROUP_BOARD_CMT_NO NOCACHE NOCYCLE;

-- 관리자 로그인 내역
CREATE SEQUENCE SEQ_ADMIN_LOGIN_NO NOCACHE NOCYCLE;

-- 관리자
CREATE SEQUENCE SEQ_ADMIN_NO NOCACHE NOCYCLE;

-- 배너
CREATE SEQUENCE SEQ_BANNER_NO NOCACHE NOCYCLE;

-- 팝업
CREATE SEQUENCE SEQ_POPUP_NO NOCACHE NOCYCLE;

-- 해시태그
CREATE SEQUENCE SEQ_TAG_NO NOCACHE NOCYCLE;

--멘토링 후기
CREATE SEQUENCE SEQ_MENTOR_REVIEW_NO NOCACHE NOCYCLE;

--멘토
CREATE SEQUENCE SEQ_MENTOR_NO NOCACHE NOCYCLE;

--멘토링 결제
CREATE SEQUENCE SEQ_MENTOR_PAYMENT_NO NOCACHE NOCYCLE;

--직무 카테고리
CREATE SEQUENCE SEQ_JOB_CATEGORY_NO NOCACHE NOCYCLE;

--멘토링 스케줄
CREATE SEQUENCE SEQ_MENTORING_SCHEDULE_NO NOCACHE NOCYCLE;

--멘토링 카테고리
CREATE SEQUENCE SEQ_MENTORING_CATEGORY_NO NOCACHE NOCYCLE;

--자유 게시판
CREATE SEQUENCE SEQ_FREEBOARD_NO NOCACHE NOCYCLE;

--자유 게시판 카테고리
CREATE SEQUENCE SEQ_FREEBOARD_CATEGORY_NO NOCACHE NOCYCLE;

--자유 게시판 첨부파일
CREATE SEQUENCE SEQ_FREEBOARD_IMG_NO NOCACHE NOCYCLE;

--자유 게시판 댓글
CREATE SEQUENCE SEQ_FREEBOARD_CMT_NO NOCACHE NOCYCLE;

--지식인 질문
CREATE SEQUENCE SEQ_KNOWLEDGE_QUESTION_NO NOCACHE NOCYCLE;

--지식인 카테고리
CREATE SEQUENCE SEQ_KNOWLEDGE_CATEGORY_NO NOCACHE NOCYCLE;

--지식인 첨부파일
CREATE SEQUENCE SEQ_KNOWLEDGE_IMG_NO NOCACHE NOCYCLE;

--지식인 답변
CREATE SEQUENCE SEQ_KNOWLEDGE_ANSWER_NO NOCACHE NOCYCLE;

--공부인증 게시판
CREATE SEQUENCE SEQ_MAKE_GRASS_NO NOCACHE NOCYCLE;

--공부인증 첨부파일
CREATE SEQUENCE SEQ_MG_IMG_NO NOCACHE NOCYCLE;
--공부인증 댓글
CREATE SEQUENCE SEQ_MG_CMT_NO NOCACHE NOCYCLE;
-- 공지사항
CREATE SEQUENCE SEQ_NOTICE_NO NOCACHE NOCYCLE;
--공지사항 댓글
CREATE SEQUENCE SEQ_NOTICE_CMT_NO NOCACHE NOCYCLE;
--공지사항 첨부파일
CREATE SEQUENCE SEQ_NOTICE_FILE_NO NOCACHE NOCYCLE;
--FAQ
CREATE SEQUENCE SEQ_FAQ_NO NOCACHE NOCYCLE;
--FAQ 이미지
CREATE SEQUENCE SEQ_NOTICE_IMG_NO NOCACHE NOCYCLE;
--문의게시판
CREATE SEQUENCE SEQ_QUESTION_BOARD_NO NOCACHE NOCYCLE;
--문의게시판 댓글
CREATE SEQUENCE SEQ_QUESTION_BOARD_CMT_NO NOCACHE NOCYCLE;
--문의게시판 파일
CREATE SEQUENCE SEQ_QUESTION_BOARD_IMG_NO NOCACHE NOCYCLE;
-- 공통카테고리
CREATE SEQUENCE SEQ_COMMON_CATEGORY_NO NOCACHE NOCYCLE;
--방문자
CREATE SEQUENCE SEQ_VISITOR_NO NOCACHE NOCYCLE;
--페이지뷰
CREATE SEQUENCE SEQ_PAGE_VIEW_NO NOCACHE NOCYCLE;